name: (Bun) Deploy Hachi Doc site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'Bun installed successfully.'
          
      - name: Update Browserslist Database
        run: |
          echo "Updating Browserslist database..."
          npx update-browserslist-db@latest

      - name: Add Bun to PATH
        run: |
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun installation
        run: |
          echo "Current PATH: $PATH" # For debugging purposes
          bun --version

      - name: Install dependencies
        run: |
          echo "Current PATH: $PATH" # For debugging purposes
          bun install

      - name: Run in Dev Mode
        run: |
          echo "Starting Bun in development mode..."
          bun run dev # Ensure this matches your actual dev script

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
